#############################

#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  lab:
    name: 实验室
    link: /lab/
    icon: icon-lab
  cml:
    name: 滴滴chameleon
    link: /cml/
    icon: icon-lab
  about:
    name: 关于我
    link: /about/
    icon: icon-about
  comment:
    name: 留言
    link: /comment/
    icon: icon-comment

#----------------------------
# 副导航
#----------------------------
subnav:
  github: "https://github.com/alanjiang1129"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RSS
#----------------------------
rss: /atom.xml

#----------------------------
# Favicon
#----------------------------
favicon: /favicon.ico

#----------------------------
# 头像url
#----------------------------
avatar: /assets/tx.jpg

#----------------------------
# 是否开启分享
#----------------------------
share: true

#----------------------------
# 侧栏是否显示微博秀
#----------------------------
weibo_show:
  enable: false
  code: <iframe id="myWeibo" width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=0&uid=2376003112&verifier=796ea597&dpc=1"></iframe>

#----------------------------
# 是否开启评论
#----------------------------
comment:
  enable: true
  owner: alanjiang1129
  repo: jp_blog
  client_id: fc95a747f032d6f9c498
  client_secret: 3fadb7a6d4d60265e5939a23e145fb860fddc7ea

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: true

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: true
  list:
    1:
      name: 易的官网
      title: 易的官网
      link: http://admin.yd-park.com
    2:
      name: 易的管理平台
      title: 易的管理平台
      link: http://admin.yd-park.com:8090
    3:
      name: 易的数据大屏
      title: 易的数据大屏
      link: http://admin.yd-park.com:8092
    4:
      name: 百度
      title: 百度搜索
      link: https://www.baidu.com
    5:
      name: 必应
      title: 必应搜索
      link: https://cn.bing.com/


#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: true
  list:
    sup:
      0:
        name: Github
        link: https://github.com/alanjiang1129
      last:
        name: 简书
        link: https://www.jianshu.com/u/23da71227054
    sub:
      sinaweibo:
        name: 新浪微博
        link: https://weibo.com/5533052073/profile?rightmod=1&wvr=6&mod=personinfo
      qq:
        name: QQ
        link: /qq
      csdn:
        name: CSDN
        link: https://i.csdn.net/#/uc/profile
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: alanJiang, 前端, Web, 江鹏, 后端开发, app, 小程序
  description: alanJiang个人前端小站

#----------------------------
# 百度分析
#----------------------------
baidu_analytics: true

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: normal
#----------------------------
# CDN
# 如: //7xs305.com1.z0.glb.clouddn.com/
# 主要以下两个目录进行 cdn 存储
#   - img 图片资源下的 thumbnail 目录
#   - css 样式资源下的 fonts 目录
#----------------------------
CDN:
